version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RUN_ADDRESS=0.0.0.0:3000
      - DATABASE_DSN=postgres://postgres:postgres@db:5432/gravitum
      - DB_POOL_WORKERS=75
      - CTX_TIMEOUT=5000
      - LOG_LEVEL=release
      - SERVICE_NAME=user-management
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gravitum
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: